--CREATE DATABASE COMPANY

--USE COMPANY

--CREATE TABLE WORKERS(
--	Id int,
--	Name nvarchar(30),
--	Surname nvarchar(50),
--	SALARY INT,
--	POSITION nvarchar(50)
--)

--INSERT INTO WORKERS VALUES
--(1,'ILKIN','BAYRAMOV',2500,'ENGINEER'),
--(2,'AYTAC','RAMAZANLI',3500,'CIO'),
--(3,'AZIM','MEMMEDLI',4500,'FOUNDER'),
--(4,'ELCIN','HEYDEROV',5500,'FOUNDER--CEO')

--INSERT INTO WORKERS VALUES
--5,'AKIF','HUSEYNOV',8000,'TEST')

--DELETE FROM WORKERS
--WHERE ID=5
--SELECT AVG(SALARY) FROM WORKERS

--SELECT * FROM WORKERS
--WHERE SALARY > (SELECT AVG(SALARY) FROM WORKERS)

--SELECT MAX(SALARY) FROM WORKERS

--SELECT MIN(SALARY) FROM WORKERS


